### ISSUE TITLE
Failed to convert input data into array: PERCENTILE_DISC? array problem

### ISSUE THREAD

**Issue by richardgmcmahon** [segasai/sqlutilpy#1]
I am using https://www.postgresql.org/docs/10/static/functions-aggregate.html#FUNCTIONS-ORDEREDSET-TABLE

This is failing:
        PERCENTILE_DISC(array[0.01,0.05,0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99])
            WITHIN GROUP (ORDER BY cnt8) AS centiles

This works
        PERCENTILE_DISC(0.25)
            WITHIN GROUP (ORDER BY cnt8) AS centiles

The full query is:

query = """
    SELECT
        /* cnt8 statistics for fixed cnt4 */
        CAST(2 AS INT) AS cnt4, count(*),
        MIN(cnt8), MAX(cnt8), MEDIAN(cnt8),
        PERCENTILE_DISC(array[0.01,0.05,0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99])
            WITHIN GROUP (ORDER BY cnt8) AS centiles
    FROM
        gaia_dr2.gaia_source AS gs
        INNER JOIN gaia_dr2_aux.gaia_source_neighbour_count AS gsnc
            ON gs.source_id = gsnc.source_id
    WHERE
        b > 80.0
        AND cnt4 = 3
    """

The error message is:

Failed to convert input data into array
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/rgm/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/rgm/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.macosx-10.6-x86_64/egg/sqlutilpy/sqlutil.py", line 180, in __converter
    res = __fromrecords(tups, dtype=dtype, intNullVal=intNullVal)
  File "build/bdist.macosx-10.6-x86_64/egg/sqlutilpy/sqlutil.py", line 137, in __fromrecords
    retval = sb.array(recList, dtype=descr)
ValueError: setting an array element with a sequence.

Traceback (most recent call last):
  File "wsdb_bugtest.py", line 79, in <module>
    user=user, password=password, asDict=True)
  File "build/bdist.macosx-10.6-x86_64/egg/sqlutilpy/sqlutil.py", line 309, in get
Exception: Child thread failed

**Comment by segasai** [comment]
I've fixed the issue with arrays  in commit 94c17cab05af777cf1be315faea6b78621c0520b (they never worked in the past). 
WIth the new version, I tested that the query works fine.
You should be able to update using pip. 
Also the arrays are not converted to full numpy arrays as PG doesn't have to return arrays of equal length, and those aren't castable to 2D numpy arrays
