### ISSUE TITLE
programmatic access to the version/revision number

### ISSUE THREAD

**Issue by richardgmcmahon** [segasai/sqlutilpy#2]
Hi Sergey,

is there a programmatic way to get get access to the version/revision number aka astropy.__version__, astroML.__version__

https://github.com/astroML/astroML/blob/master/setup.py

**Comment by segasai** [comment]
Hi Richard, 

There is now (starting from current release).
```
 In [5]: import sqlutilpy

 In [6]: print (sqlutilpy.__version__)
0.0.6

```
