### ISSUE TITLE
New fonctionnality : join_cols

### ISSUE THREAD

**Issue by chmanu** [segasai/sqlutilpy#3]
Hello,
I like your tool and should be very interesting for me.
But I my context, I used to use very large numpy array and should better to store into array postgresql column. 
Example : 
time | postition | vector_of_value
where position is an array of 3 real and value is an array of 250 real

I tried to adapt the code by adding a join_cols parameter (where is described how to map and join : position:x,y,z;vector_of_value:val1,val2,val3,...val250) but the __print_arrays function doesn't work with array of strings.

Do you thing you can take into account this kind of needs in a next release ?

Thanks in advance.
Manu

**Comment by segasai** [comment]
Hi,

I agree that functionality would be good, but I don't think I know an easy way of fast printing of an array. And I certainly don't want to slow down the existing code to enable joins with arrays. So unless I figure out an efficient way of implementing what you want, I probably won't do it.

Sergey
